apiVersion: apps/v1
kind: Deployment
metadata: 
  name: authentication-service
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: authentication-service
  template: 
    metadata:
      labels:
        app: authentication-service
    spec: 
      containers: 
        - name: authentication-service
          image: "philip/authentication -service:1.0.0"          
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env: 
            - name: DSN  
              value: "host=host.minikube.Internal"   
          ports:
            - containerPort: 8081  
---

apiVersion: v1 
kind: Service
metadata: 
  name: authentication-service
spec: 
  selector:
    app: authentication-service
  ports: 
    - protocol: TCP
      name: web-port
      port: 8081
      targetPort: 8081    