version: '3'

#declare the list of services we want to launch
services:
 

  broker-service:
    build: #build the image from the golang source 
      context: ./../broker-service        #declares its dir
      dockerfile: ./../broker-service/broker-service.dockerfile   #get the docker file from the broker-service dir
    restart: always #restart incase it dies 
    ports:
      - "8080:80" #mappin the port , tells docker to listen on port 8080 on  your local machine, and forward it to port 80 inside docker
    deploy:
      mode: replicated
      replicas: 1  #listens to 1 port only


  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"





  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432" #5432 on the machine : 5432 in the docker container
    
    restart: "always"  
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: philippians
      POSTGRES_DB: postgres
    #volumes set for data to persist
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/     
